---
# tasks file for common

- name: set timezone to Europe/Moscow
  timezone:
    name: "{{ timezone_name }}"

- block:
    - name: create a swap file
      shell: fallocate -l {{ swap_size }} {{ swap_file }}
      args:
        creates: "{{ swap_file }}"

    - name: set the correct permissions
      file:
        path: "{{ swap_file }}"
        owner: root
        group: root
        mode: '0600'

    - name: make the file a swap file
      shell: mkswap {{ swap_file }}
      when: ansible_facts.swapfree_mb == 0

    - name: enable the swap file
      shell: swapon {{ swap_file }}
      when: ansible_facts.swapfree_mb == 0

    - name: add swap file to fstab
      mount:
        name: none
        src: "{{ swap_file }}"
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

